### ISSUE TITLE
no seed peers,  the wallet can not connect

### ISSUE THREAD

**Issue by LinanCodes** [turtlegold/TurtleGold#10]
no seed peers,  the wallet can not connect

Failed to connect to any of seed peers, continuing without seeds**

**Comment by MaayanSG** [comment]
Seed nodes seem fine...
If this problem continues, use a remote node

**Comment by MaayanSG** [comment]
Do in cmd or make a .bat with the following
For windows: turtlegoldd -r trtg.turbomine.co:42061
For Linux: ./turtlegoldd -r trtg.turbomine.co:42061

**Comment by LinanCodes** [comment]
Follow the instructions ,The problem exists!   wallet version: 0.1.3,  Please fix it as soon as possible

**Comment by LinanCodes** [comment]
No user, no value.   that is a big problem, resolve the issue as soon as possible,   the community can grow.

**Comment by LinanCodes** [comment]
The platform :  windows | problem exists
The platform :  Linux |  OK

check the platform with windows

**Comment by LinanCodes** [comment]
[p2pstate.zip](https://github.com/turtlegold/TurtleGold/files/3193651/p2pstate.zip)

sync nodes ,  new  p2pstate.bin,  update

**Comment by MaayanSG** [comment]
Firewall could be causing a problem... for help with anything else visit https://discord.gg/bHUnRqx
