### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by LeoCornelius** [turtlegold/TurtleGold#5]
Meet kegcoin gold, the cryptocurrency of the future!
Fast block times (30 seconds) and super low fees allow easy use in everyday transactions
Ticker: KEG
Block time 30 seconds
Block reward (currently) 23 KEG
Website: http://kegcoin.tk/
Discord: https://discord.gg/DzQMNJ7
Pool: http://mine2.live/
BitcoinTalk: https://bitcointalk.org/index.php?topic=5120650.new#new lol

**Comment by MaayanSG** [comment]
🖕
